# from PyQt6 import QtCore, QtWidgets


# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(802, 600)
#         self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.label = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label.setGeometry(QtCore.QRect(290, 70, 211, 41))
#         self.label.setObjectName("label")
#         self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_2.setGeometry(QtCore.QRect(210, 150, 71, 21))
#         self.label_2.setObjectName("label_2")
#         self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_3.setGeometry(QtCore.QRect(210, 200, 81, 21))
#         self.label_3.setObjectName("label_3")
#         self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
#         self.label_4.setGeometry(QtCore.QRect(210, 250, 111, 21))
#         self.label_4.setObjectName("label_4")
#         self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
#         self.lineEdit.setGeometry(QtCore.QRect(320, 150, 261, 21))
#         self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
#         self.lineEdit.setObjectName("lineEdit")
#         self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
#         self.lineEdit_2.setGeometry(QtCore.QRect(320, 200, 261, 21))
#         self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
#         self.lineEdit_2.setObjectName("lineEdit_2")
#         self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
#         self.lineEdit_3.setGeometry(QtCore.QRect(320, 250, 261, 21))
#         self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
#         self.lineEdit_3.setObjectName("lineEdit_3")
#         self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
#         self.pushButton.setGeometry(QtCore.QRect(300, 320, 191, 51))
#         self.pushButton.setObjectName("pushButton")
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 18))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)

#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)

#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Welcome to PEATA!</span></p></body></html>"))
#         self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Client ID</span></p></body></html>"))
#         self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Client Key</span></p></body></html>"))
#         self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Client Secret</span></p></body></html>"))
#         self.pushButton.setText(_translate("MainWindow", "Log In"))
