# Form implementation generated from reading ui file 'D:\PEATA-project\PEATA\PEATA\gui\ui\login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(859, 514)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(320, 80, 211, 41))
        self.title.setObjectName("title")
        self.client_id = QtWidgets.QLabel(parent=self.centralwidget)
        self.client_id.setGeometry(QtCore.QRect(240, 160, 71, 21))
        self.client_id.setObjectName("client_id")
        self.client_key = QtWidgets.QLabel(parent=self.centralwidget)
        self.client_key.setGeometry(QtCore.QRect(240, 210, 81, 21))
        self.client_key.setObjectName("client_key")
        self.client_secret = QtWidgets.QLabel(parent=self.centralwidget)
        self.client_secret.setGeometry(QtCore.QRect(240, 260, 111, 21))
        self.client_secret.setObjectName("client_secret")
        self.client_id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.client_id_input.setGeometry(QtCore.QRect(350, 160, 261, 21))
        self.client_id_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.client_id_input.setObjectName("client_id_input")
        self.client_key_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.client_key_input.setGeometry(QtCore.QRect(350, 210, 261, 21))
        self.client_key_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.client_key_input.setObjectName("client_key_input")
        self.client_secret_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.client_secret_input.setGeometry(QtCore.QRect(350, 260, 261, 21))
        self.client_secret_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.client_secret_input.setObjectName("client_secret_input")
        self.login_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(240, 310, 371, 51))
        self.login_button.setObjectName("login_button")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=LoginWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 859, 33))
        self.menuBar.setObjectName("menuBar")
        LoginWindow.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.title.setText(_translate("LoginWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Welcome to PEATA!</span></p></body></html>"))
        self.client_id.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Client Id</span></p></body></html>"))
        self.client_key.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Client Key</span></p></body></html>"))
        self.client_secret.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Client Secret</span></p></body></html>"))
        self.login_button.setText(_translate("LoginWindow", "Log In"))
