REGION_CODES = {
    'Afghanistan (AF)': 'AF', 'Albania (AL)': 'AL', 'Algeria (DZ)': 'DZ',
    'Angola (AO)': 'AO', 'Anguilla (AI)': 'AI', 'Argentina (AR)': 'AR',
    'Australia (AU)': 'AU', 'Austria (AT)': 'AT', 'Azerbaijan (AZ)': 'AZ',
    'Bahrain (BH)': 'BH', 'Bangladesh (BD)': 'BD', 'Belarus (BY)': 'BY',
    'Belgium (BE)': 'BE', 'Benin (BJ)': 'BJ', 'Bolivia (BO)': 'BO',
    'Botswana (BW)': 'BW', 'Brazil (BR)': 'BR', 'Brunei (BN)': 'BN',
    'Bulgaria (BG)': 'BG', 'Cambodia (KH)': 'KH', 'Cameroon (CM)': 'CM',
    'Canada (CA)': 'CA', 'Chile (CL)': 'CL', 'Colombia (CO)': 'CO',
    'Congo (CD)': 'CD', 'Congo (CG)': 'CG', 'Costa Rica (CR)': 'CR',
    'Croatia (HR)': 'HR', 'Czech Republic (CZ)': 'CZ', 'Denmark (DK)': 'DK',
    'Dominican Republic (DO)': 'DO', 'Ecuador (EC)': 'EC', 'Egypt (EG)': 'EG',
    'El Salvador (SV)': 'SV', 'Ethiopia (ET)': 'ET', 'Faroe Islands (FO)': 'FO',
    'Finland (FI)': 'FI', 'France (FR)': 'FR', 'Gabon (GA)': 'GA',
    'Gambia (GM)': 'GM', 'Georgia (GE)': 'GE', 'Germany (DE)': 'DE',
    'Ghana (GH)': 'GH', 'Greece (GR)': 'GR', 'Guadeloupe (GP)': 'GP',
    'Guatemala (GT)': 'GT', 'Guinea-Bissau (GW)': 'GW', 'Guyana (GY)': 'GY',
    'Haiti (HT)': 'HT', 'Honduras (HN)': 'HN', 'Hungary (HU)': 'HU',
    'Iceland (IS)': 'IS', 'Indonesia (ID)': 'ID', 'Iraq (IQ)': 'IQ',
    'Ireland (IE)': 'IE', 'Israel (IL)': 'IL', 'Italy (IT)': 'IT',
    'Ivory Coast (CI)': 'CI', 'Jamaica (JM)': 'JM', 'Japan (JP)': 'JP',
    'Jordan (JO)': 'JO', 'Kazakhstan (KZ)': 'KZ', 'Kenya (KE)': 'KE',
    'Kuwait (KW)': 'KW', 'Kyrgyzstan (KG)': 'KG', 'Laos (LA)': 'LA',
    'Latvia (LV)': 'LV', 'Lebanon (LB)': 'LB', 'Liberia (LR)': 'LR',
    'Libya (LY)': 'LY', 'Lithuania (LT)': 'LT', 'Luxembourg (LU)': 'LU',
    'Madagascar (MG)': 'MG', 'Malaysia (MY)': 'MY', 'Maldives (MV)': 'MV',
    'Mali (ML)': 'ML', 'Malta (MT)': 'MT', 'Mauritania (MR)': 'MR',
    'Mauritius (MU)': 'MU', 'Mexico (MX)': 'MX', 'Moldova (MD)': 'MD',
    'Morocco (MA)': 'MA', 'Mozambique (MZ)': 'MZ', 'Myanmar (MM)': 'MM',
    'Nepal (NP)': 'NP', 'Netherlands (NL)': 'NL', 'Nicaragua (NI)': 'NI',
    'Nigeria (NG)': 'NG', 'North Macedonia (MK)': 'MK', 'Norway (NO)': 'NO',
    'Oman (OM)': 'OM', 'Pakistan (PK)': 'PK', 'Panama (PA)': 'PA',
    'Paraguay (PY)': 'PY', 'Peru (PE)': 'PE', 'Philippines (PH)': 'PH',
    'Poland (PL)': 'PL', 'Portugal (PT)': 'PT', 'Puerto Rico (PR)': 'PR',
    'Qatar (QA)': 'QA', 'Reunion (RE)': 'RE', 'Romania (RO)': 'RO',
    'Saudi Arabia (SA)': 'SA', 'Senegal (SN)': 'SN', 'Serbia (RS)': 'RS',
    'Sierra Leone (SL)': 'SL', 'Singapore (SG)': 'SG', 'Slovakia (SK)': 'SK',
    'Somalia (SO)': 'SO', 'South Africa (ZA)': 'ZA', 'South Korea (KR)': 'KR',
    'Spain (ES)': 'ES', 'Sri Lanka (LK)': 'LK', 'Sudan (SD)': 'SD',
    'Suriname (SR)': 'SR', 'Sweden (SE)': 'SE', 'Switzerland (CH)': 'CH',
    'Taiwan (TW)': 'TW', 'Tanzania (TZ)': 'TZ', 'Thailand (TH)': 'TH',
    'Togo (TG)': 'TG', 'Trinidad and Tobago (TT)': 'TT', 'Tunisia (TN)': 'TN',
    'Turkey (TR)': 'TR', 'Turkmenistan (TM)': 'TM', 'UK (GB)': 'GB',
    'USA (US)': 'US', 'Uganda (UG)': 'UG', 'Ukraine (UA)': 'UA',
    'United Arab Emirates (AE)': 'AE', 'Uruguay (UY)': 'UY', 'Uzbekistan (UZ)': 'UZ',
    'Venezuela (VE)': 'VE', 'Vietnam (VN)': 'VN', 'Zambia (ZM)': 'ZM'
}